apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-antony-deployment"
  labels:
{{ include "project.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.antony.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-antony-deployment"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-antony-deployment"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-antony-deployment-container
          image: "{{ .Values.antony.image.repository }}:{{ .Values.antony.image.tag }}"
          imagePullPolicy: {{ .Values.antony.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.antony.apiPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.antony.deployment.resources | nindent 12 }}
