apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-roger-service"
  labels:
{{ include "project.labels" . | indent 4 }}
spec:
  selector:
    app: "{{ .Release.Name }}-roger-deployment"
  ports:
    - port: {{ .Values.roger.service.port }}
      targetPort: {{ .Values.roger.apiPort }}
  type: {{ .Values.roger.service.type }}